/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author HPPC & slep
 */
public class GameSpeed extends javax.swing.JFrame {

    Game game;

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GameSpeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GameSpeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GameSpeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GameSpeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameSpeed().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jrbEasy;
    private javax.swing.JRadioButton jrbHard;
    private javax.swing.JRadioButton jrbMedium;

    /**
     * Creates new form GameSpeed
     */
    public GameSpeed(Game g) {
        initComponents();
        game = g;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jrbEasy = new javax.swing.JRadioButton();
        jrbMedium = new javax.swing.JRadioButton();
        jrbHard = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Difficulty Menu");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Select Your Difficulty");

        buttonGroup1.add(jrbEasy);
        jrbEasy.setText("Easy");
        jrbEasy.addActionListener(evt -> jrbEasyActionPerformed(evt));

        buttonGroup1.add(jrbMedium);
        jrbMedium.setText("Medium");
        jrbMedium.addActionListener(evt -> jrbMediumActionPerformed(evt));

        buttonGroup1.add(jrbHard);
        jrbHard.setText("Hard");
        jrbHard.addActionListener(evt -> jrbHardActionPerformed(evt));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jrbEasy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jrbMedium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jrbHard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)
                                .addComponent(jrbEasy)
                                .addGap(36, 36, 36)
                                .addComponent(jrbMedium)
                                .addGap(36, 36, 36)
                                .addComponent(jrbHard)
                                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEasyActionPerformed
        game.paddleSpeed = 7;
        //game.delay = 10;
        game.t.start();
        this.dispose();
    }//GEN-LAST:event_jrbEasyActionPerformed

    private void jrbMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMediumActionPerformed
        game.paddleSpeed = 7;
        //game.delay = 7;
        game.xBall = 3;
        game.yBall = 3;
        game.t.start();
        this.dispose();
    }//GEN-LAST:event_jrbMediumActionPerformed

    private void jrbHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbHardActionPerformed
        game.paddleSpeed = 8;
        //game.delay = 4;
        game.xBall = 4;
        game.yBall = 4;
        game.t.start();
        this.dispose();
    }//GEN-LAST:event_jrbHardActionPerformed
    // End of variables declaration//GEN-END:variables
}
